// Ship Card
// Local-first shipping cards with stable ids based on UTC seed (TS).
// ASCII only.

function fnv1a32(str){
  let h = 0x811c9dc5;
  for (let i = 0; i < str.length; i++){
    h ^= str.charCodeAt(i);
    h = Math.imul(h, 0x01000193);
  }
  return h >>> 0;
}

function u32ToHex(u){
  return (u >>> 0).toString(16).padStart(8, "0");
}

function nowUtcCompact(){
  // YYYYMMDDTHHMMZ
  const d = new Date();
  const pad2 = (n) => String(n).padStart(2, "0");
  return (
    d.getUTCFullYear() +
    pad2(d.getUTCMonth() + 1) +
    pad2(d.getUTCDate()) +
    "T" +
    pad2(d.getUTCHours()) +
    pad2(d.getUTCMinutes()) +
    "Z"
  );
}

function clampStr(s, max){
  const t = String(s || "");
  if (t.length <= max) return t;
  return t.slice(0, max);
}

function safeSlug(s){
  return String(s || "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 64);
}

function storageKey(){
  return "shipcard:history:v1";
}

function loadHistory(){
  try {
    const raw = localStorage.getItem(storageKey());
    if (!raw) return [];
    const arr = JSON.parse(raw);
    if (!Array.isArray(arr)) return [];
    const out = [];
    for (const it of arr){
      if (!it || typeof it !== "object") continue;
      out.push({
        savedUtc: String(it.savedUtc || ""),
        ts: String(it.ts || ""),
        slug: String(it.slug || ""),
        title: String(it.title || ""),
        changed: String(it.changed || ""),
        next: String(it.next || "")
      });
    }
    return out;
  } catch {
    return [];
  }
}

function saveHistory(items){
  try {
    localStorage.setItem(storageKey(), JSON.stringify(items || []));
    return true;
  } catch {
    return false;
  }
}

function makeId(ts, title){
  const base = String(ts || "") + "::" + String(title || "");
  return u32ToHex(fnv1a32(base));
}

function makeLink(state){
  const st = state || {};
  const p = new URLSearchParams();
  if (st.ts) p.set("ts", st.ts);
  if (st.slug) p.set("slug", st.slug);
  if (st.title) p.set("title", st.title);
  if (st.changed) p.set("changed", st.changed);
  if (st.next) p.set("next", st.next);
  const qs = p.toString();
  return window.location.origin + window.location.pathname + (qs ? ("?" + qs) : "");
}

function readQuery(){
  const p = new URLSearchParams(window.location.search || "");
  return {
    ts: p.get("ts") || "",
    slug: p.get("slug") || "",
    title: p.get("title") || "",
    changed: p.get("changed") || "",
    next: p.get("next") || ""
  };
}

function setQuery(state){
  const st = state || {};
  const p = new URLSearchParams();
  if (st.ts) p.set("ts", st.ts);
  if (st.slug) p.set("slug", st.slug);
  if (st.title) p.set("title", st.title);
  if (st.changed) p.set("changed", st.changed);
  if (st.next) p.set("next", st.next);
  const qs = p.toString();
  const url = window.location.pathname + (qs ? ("?" + qs) : "");
  window.history.replaceState(null, "", url);
}

function buildMarkdown(state){
  const st = state || {};
  const ts = String(st.ts || "").trim();
  const title = String(st.title || "").trim() || "(untitled ship card)";
  const changed = String(st.changed || "").trim();
  const next = String(st.next || "").trim();
  const id = makeId(ts, title);

  const lines = [];
  lines.push(`# Ship Card: ${title}`);
  lines.push("");
  lines.push(`- ts: ${ts || "(empty)"}`);
  lines.push(`- id: ${id}`);
  lines.push(`- savedUtc: ${nowUtcCompact()}`);
  lines.push("");

  lines.push("## What changed");
  lines.push("");
  lines.push(changed ? changed : "(empty)");
  lines.push("");

  lines.push("## Next step");
  lines.push("");
  lines.push(next ? next : "(empty)");
  lines.push("");

  lines.push("---");
  lines.push("Generated by Ship Card (local-first):");
  lines.push(makeLink(st));
  lines.push("");
  return { md: lines.join("\n"), id };
}

async function copyToClipboard(text){
  await navigator.clipboard.writeText(text);
}

function downloadText(filename, text, mime){
  const blob = new Blob([text], { type: mime || "text/plain" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

function main(){
  const elTs = document.getElementById("ts");
  const elSlug = document.getElementById("slug");
  const elTitle = document.getElementById("title");
  const elChanged = document.getElementById("changed");
  const elNext = document.getElementById("next");

  const elOut = document.getElementById("out");
  const elHistory = document.getElementById("history");
  const elKId = document.getElementById("kId");
  const elKSaved = document.getElementById("kSaved");

  const btnSave = document.getElementById("btnSave");
  const btnCopy = document.getElementById("btnCopy");
  const btnLink = document.getElementById("btnLink");
  const btnDownload = document.getElementById("btnDownload");
  const btnNew = document.getElementById("btnNew");

  const btnExport = document.getElementById("btnExport");
  const btnImport = document.getElementById("btnImport");
  const btnClear = document.getElementById("btnClear");
  const fileImport = document.getElementById("fileImport");

  function getState(){
    return {
      ts: clampStr((elTs && elTs.value) || "", 32),
      slug: safeSlug((elSlug && elSlug.value) || ""),
      title: clampStr((elTitle && elTitle.value) || "", 160),
      changed: clampStr((elChanged && elChanged.value) || "", 5000),
      next: clampStr((elNext && elNext.value) || "", 240)
    };
  }

  function setState(st){
    const s = st || {};
    if (elTs) elTs.value = String(s.ts || "");
    if (elSlug) elSlug.value = String(s.slug || "");
    if (elTitle) elTitle.value = String(s.title || "");
    if (elChanged) elChanged.value = String(s.changed || "");
    if (elNext) elNext.value = String(s.next || "");
  }

  function render(){
    const st = getState();
    if (elTs && !String(st.ts || "").trim()){
      elTs.value = nowUtcCompact();
      st.ts = elTs.value;
    }

    const out = buildMarkdown(st);
    if (elOut) elOut.value = out.md;
    if (elKId) elKId.textContent = `id: ${out.id}`;
    if (elKSaved) elKSaved.textContent = `saved: ${nowUtcCompact()}`;

    setQuery(st);
    return { st, out };
  }

  function renderHistory(){
    if (!elHistory) return;
    const items = loadHistory();
    elHistory.innerHTML = "";

    if (!items.length){
      const empty = document.createElement("div");
      empty.className = "historyMeta";
      empty.textContent = "(No saved cards yet.)";
      elHistory.appendChild(empty);
      return;
    }

    for (let i = 0; i < items.length; i++){
      const it = items[i];
      const id = makeId(it.ts, it.title);

      const row = document.createElement("div");
      row.className = "historyItem";

      const meta = document.createElement("div");
      meta.className = "historyMeta";
      meta.textContent = `saved ${it.savedUtc || "-"} | ts ${it.ts || "-"} | id ${id}`;

      const title = document.createElement("div");
      title.className = "historyTitle";
      title.textContent = String(it.title || "(untitled)");

      const btns = document.createElement("div");
      btns.className = "historyBtns";

      const bLoad = document.createElement("button");
      bLoad.type = "button";
      bLoad.textContent = "Load";
      bLoad.addEventListener("click", () => {
        setState(it);
        render();
      });

      const bCopy = document.createElement("button");
      bCopy.type = "button";
      bCopy.textContent = "Copy";
      bCopy.addEventListener("click", async () => {
        const out = buildMarkdown(it);
        try {
          await copyToClipboard(out.md);
        } catch {
          alert("Clipboard unavailable.");
        }
      });

      const bLink = document.createElement("button");
      bLink.type = "button";
      bLink.textContent = "Link";
      bLink.addEventListener("click", async () => {
        const url = makeLink(it);
        try {
          await copyToClipboard(url);
        } catch {
          alert(url);
        }
      });

      const bRemove = document.createElement("button");
      bRemove.type = "button";
      bRemove.className = "ghost";
      bRemove.textContent = "Remove";
      bRemove.addEventListener("click", () => {
        const items2 = loadHistory();
        const next = [];
        for (let j = 0; j < items2.length; j++){
          if (j !== i) next.push(items2[j]);
        }
        saveHistory(next);
        renderHistory();
      });

      btns.appendChild(bLoad);
      btns.appendChild(bCopy);
      btns.appendChild(bLink);
      btns.appendChild(bRemove);

      row.appendChild(meta);
      row.appendChild(title);
      row.appendChild(btns);

      elHistory.appendChild(row);
    }
  }

  function saveCurrentToHistory(){
    const { st } = render();
    const items = loadHistory();

    const saved = {
      savedUtc: nowUtcCompact(),
      ts: String(st.ts || "").trim(),
      slug: String(st.slug || ""),
      title: String(st.title || ""),
      changed: String(st.changed || ""),
      next: String(st.next || "")
    };

    // Keep unique by (ts + title).
    const sig = saved.ts + "|" + saved.title;
    const nextItems = [saved];
    for (const it of items){
      const sig2 = String(it.ts || "") + "|" + String(it.title || "");
      if (sig2 === sig) continue;
      nextItems.push(it);
      if (nextItems.length >= 24) break;
    }

    saveHistory(nextItems);
    renderHistory();
    return saved;
  }

  if (btnSave) btnSave.addEventListener("click", () => { saveCurrentToHistory(); });

  if (btnCopy) btnCopy.addEventListener("click", async () => {
    const { out } = render();
    try {
      await copyToClipboard(out.md);
    } catch {
      alert("Clipboard unavailable. Use download.");
    }
  });

  if (btnLink) btnLink.addEventListener("click", async () => {
    const { st } = render();
    const url = makeLink(st);
    try {
      await copyToClipboard(url);
    } catch {
      alert(url);
    }
  });

  if (btnDownload) btnDownload.addEventListener("click", () => {
    const { st, out } = render();
    const base = safeSlug(st.slug || st.title || "ship-card") || "ship-card";
    const name = `ship-card-${base}-${out.id}.md`;
    downloadText(name, out.md, "text/markdown");
  });

  if (btnNew) btnNew.addEventListener("click", () => {
    setState({ ts: nowUtcCompact(), slug: "", title: "", changed: "", next: "" });
    render();
  });

  if (btnExport) btnExport.addEventListener("click", () => {
    const data = { version: 1, exportedUtc: nowUtcCompact(), items: loadHistory() };
    const name = `ship-card-backup-${nowUtcCompact()}.json`;
    downloadText(name, JSON.stringify(data, null, 2), "application/json");
  });

  if (btnImport && fileImport){
    btnImport.addEventListener("click", () => {
      fileImport.value = "";
      fileImport.click();
    });

    fileImport.addEventListener("change", () => {
      const f = fileImport.files && fileImport.files[0];
      if (!f) return;
      const r = new FileReader();
      r.onload = () => {
        try {
          const txt = String(r.result || "");
          const obj = JSON.parse(txt);
          const items = Array.isArray(obj.items) ? obj.items : [];
          const ok = window.confirm("Import backup and replace existing history for Ship Card?");
          if (!ok) return;
          saveHistory(items);
          renderHistory();
          alert("Imported " + String(items.length) + " cards.");
        } catch {
          alert("Import failed: invalid JSON");
        }
      };
      r.onerror = () => { alert("Import failed: could not read file"); };
      r.readAsText(f);
    });
  }

  if (btnClear) btnClear.addEventListener("click", () => {
    const ok = window.confirm("Clear Ship Card history? This removes local-only data.");
    if (!ok) return;
    saveHistory([]);
    renderHistory();
  });

  // Live render.
  const debounce = { t: null };
  function renderSoon(){
    if (debounce.t) clearTimeout(debounce.t);
    debounce.t = setTimeout(() => { render(); }, 120);
  }

  if (elTs) elTs.addEventListener("input", renderSoon);
  if (elSlug) elSlug.addEventListener("input", renderSoon);
  if (elTitle) elTitle.addEventListener("input", renderSoon);
  if (elChanged) elChanged.addEventListener("input", renderSoon);
  if (elNext) elNext.addEventListener("input", renderSoon);

  // Initial load: query or defaults.
  const q = readQuery();
  if (q.ts || q.title || q.changed || q.next || q.slug){
    setState(q);
  } else {
    setState({ ts: nowUtcCompact(), slug: "", title: "", changed: "", next: "" });
  }

  render();
  renderHistory();
}

main();
